#spring.application.name=java-apr25-spring-controller

#spring.datasource.url=jdbc:h2:mem:appdb
#spring.datasource.username=sa
#spring.datasource.password=sa123

#spring.h2.console.enabled=true

spring:
  application:
    name: java-apr25-spring-controller
  datasource:
    url: jdbc:h2:./appdb
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081
