package org.example.javaapr25springcontroller.util;

public interface SqlConstants {

	String FETCH_ALL_PRODUCT = "SELECT * FROM PRODUCT";

	String FETCH_PRODUCT_BY_ID = "SELECT * FROM PRODUCT WHERE PRODUCT_ID = ?";

	String ADD_PRODUCT =  "INSERT INTO PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_DESC) VALUES (?,?,?)";

	String UPDATE_PRODUCT = "UPDATE PRODUCT SET PRODUCT_NAME=?, PRODUCT_DESC=? WHERE PRODUCT_ID=?";

	String DELETE_PRODUCT = "DELETE FROM PRODUCT WHERE PRODUCT_ID=?";

	// Practice CRUD operations.
}
